---
abstract: 'Import SQL files into MySQL'
author: []
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-DoubleUp
provides:
  App::DoubleUp:
    file: lib/App/DoubleUp.pm
    version: v0.2.4
requires:
  DBI: 0
  SQL::SplitStatement: 0.05003
  YAML: 0.71
resources:
  license: http://dev.perl.org/licenses/
version: v0.2.4
