---
name: App-DoubleUp
version: v0.1.0
author: []
abstract: Import SQL files into MySQL
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  DBI: 0
configure_requires:
  Module::Build: 0.340201
provides:
  App::DoubleUp:
    file: lib/App/DoubleUp.pm
    version: v0.1.0
generated_by: Module::Build version 0.340201
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
